steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/nice-particle-416210/youtubesearch/youtubesearch:latest', .]

  # Docker push to Google Artifact Registry r
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/nice-particle-416210/youtubesearch/youtubesearch:latest']
