name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: nice-particle-416210
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: nice-particle-416210}
        run: |
          gcloud auth configure-docker europe-west1.pkg.dev
          docker build -t europe-west1-docker.pkg.dev/nice-particle-416210/youtubesearch:latest .
          docker push europe-west1-docker.pkg.dev/nice-particle-416210/youtubesearch:latest


