name: CI/CD with Google Cloud Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image in Google Cloud Build
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: nice-particle-416210
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Run Cloud Build
        run: |
          gcloud builds submit --tag=gcr.io/nice-particle-416210/youtubesearch/youtubesearch:latest .
